# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.environment/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.environment/**'

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache node_modules/
        uses: actions/cache@v1
        id: cache_node_modules
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install Dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install
        
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  
      - name: Deploy Application
        run: sudo /opt/services/run-deploy.sh ${{ github.event.repository.name }}
